name: Building
main: com.gmail.zhou1992228.building.Building
version: 1.0
load: POSTWORLD
depend: [Multiverse-Core]
commands:
  build:
    description: test if a building ok
    usage: /<command>
  collect:
    description: Collection the resources from the building.
    usage: /<command> [count]
  put:
    description:  the resources from the building.
    usage: /<command> [count]
  testbuild:
    description:  build a building, op only
    usage: /<command> <building_name>
  xx:
    description: info of a building
    usage: /<command>
  friend:
    description: add player as your friend
    usage: /<command> <id>
  unfriend:
    description: remove player from your friend list
    usage: /<command> <id>
  template:
    description: test
    usage: /<command>