name: Building
main: com.gmail.zhou1992228.building.Building
version: 1.0
commands:
  build:
    description: test if a building ok
    usage: /<command>
  collect:
    description: Collection the resources from the building.
    usage: /<command> [count]
  put:
    description:  the resources from the building.
    usage: /<command> [count]
  testbuild:
    description:  build a building, op only
    usage: /<command> <building_name>